-- Create a specific ELT _warehouse
USE ROLE ORGADMIN;
CREATE WAREHOUSE IF NOT EXISTS ELT_WAREHOUSE WITH WAREHOUSE_SIZE = 'XSMALL' WAREHOUSE_TYPE = 'STANDARD' AUTO_SUSPEND = 180 AUTO_RESUME = TRUE MIN_CLUSTER_COUNT = 1 MAX_CLUSTER_COUNT = 1 SCALING_POLICY = 'STANDARD'; 

-- Apply commenting to the ELT_warehouse
USE ROLE ORGADMIN;
ALTER WAREHOUSE IF EXISTS ELT_WAREHOUSE SET COMMENT = 'Dedicated ELT workload warehouse.';

-- Creating a bronze Database
USE ROLE ORGADMIN;
CREATE
OR REPLACE DATABASE BRONZE DATA_RETENTION_TIME_IN_DAYS = 1 COMMENT = 'This is the Bronze database for raw, unprocessed data.';

-- Creating a silver Database
USE ROLE ORGADMIN;
CREATE
OR REPLACE DATABASE SILVER DATA_RETENTION_TIME_IN_DAYS = 1 COMMENT = 'This is the Silver database for processed, system-defined data.';

-- Creating a AWS Bronze Schema
USE ROLE ORGADMIN;
USE DATABASE BRONZE;
CREATE
or REPLACE SCHEMA AWS COMMENT = 'This schema contains all the AWS related raw data tables';

-- Creating a AWS Silver Schema
USE ROLE ORGADMIN;
USE DATABASE SILVER;
CREATE SCHEMA IF NOT EXISTS AWS COMMENT = 'This schema contains all the AWS related processed tables';

-- Apply commenting to the columns within AWS_Raw_Data
USE ROLE ORGADMIN;
USE DATABASE BRONZE;
ALTER TABLE
    BRONZE.AWS.AWS_RAW_DATA ALTER PRODUCT_ID COMMENT 'Product ID';
USE ROLE ORGADMIN;
USE DATABASE BRONZE;
ALTER TABLE
    BRONZE.AWS.AWS_RAW_DATA ALTER PRODUCT_NAME COMMENT 'Name of the Product';
USE ROLE ORGADMIN;
USE DATABASE BRONZE;
ALTER TABLE
    BRONZE.AWS.AWS_RAW_DATA ALTER CATEGORY COMMENT 'Category of the Product';
USE ROLE ORGADMIN;
USE DATABASE BRONZE;
ALTER TABLE
    BRONZE.AWS.AWS_RAW_DATA ALTER DISCOUNTED_PRICE COMMENT 'Discounted Price of the Product';
USE ROLE ORGADMIN;
USE DATABASE BRONZE;
ALTER TABLE
    BRONZE.AWS.AWS_RAW_DATA ALTER ACTUAL_PRICE COMMENT 'Actual Price of the Product';
USE ROLE ORGADMIN;
USE DATABASE BRONZE;
ALTER TABLE
    BRONZE.AWS.AWS_RAW_DATA ALTER DISCOUNT_PERCENTAGE COMMENT 'Percentage of Discount for the Product';
USE ROLE ORGADMIN;
USE DATABASE BRONZE;
ALTER TABLE
    BRONZE.AWS.AWS_RAW_DATA ALTER RATING COMMENT 'Rating of the Product';
USE ROLE ORGADMIN;
USE DATABASE BRONZE;
ALTER TABLE
    BRONZE.AWS.AWS_RAW_DATA ALTER RATING_COUNT COMMENT 'Number of people who voted for the Amazon rating';
USE ROLE ORGADMIN;
USE DATABASE BRONZE;
ALTER TABLE
    BRONZE.AWS.AWS_RAW_DATA ALTER ABOUT_PRODUCT COMMENT 'Description about the Product';
USE ROLE ORGADMIN;
USE DATABASE BRONZE;
ALTER TABLE
    BRONZE.AWS.AWS_RAW_DATA ALTER USER_ID COMMENT 'ID of the user who wrote review for the Product';
USE ROLE ORGADMIN;
USE DATABASE BRONZE;
ALTER TABLE
    BRONZE.AWS.AWS_RAW_DATA ALTER USER_NAME COMMENT 'Name of the user who wrote review for the Product';
USE ROLE ORGADMIN;
USE DATABASE BRONZE;
ALTER TABLE
    BRONZE.AWS.AWS_RAW_DATA ALTER REVIEW_ID COMMENT 'ID of the user review';
USE ROLE ORGADMIN;
USE DATABASE BRONZE;
ALTER TABLE
    BRONZE.AWS.AWS_RAW_DATA ALTER REVIEW_TITLE COMMENT 'Short review';
USE ROLE ORGADMIN;
USE DATABASE BRONZE;
ALTER TABLE
    BRONZE.AWS.AWS_RAW_DATA ALTER REVIEW_CONTENT COMMENT 'Long review';
USE ROLE ORGADMIN;
USE DATABASE BRONZE;
ALTER TABLE
    BRONZE.AWS.AWS_RAW_DATA ALTER IMG_LINK COMMENT 'Image Link of the Product';
USE ROLE ORGADMIN;
USE DATABASE BRONZE;
ALTER TABLE
    BRONZE.AWS.AWS_RAW_DATA ALTER PRODUCT_LINK COMMENT 'Official Website Link of the Product';

-- Create a dynamic product dimension table
USE DATABASE SILVER;
CREATE OR REPLACE DYNAMIC TABLE SILVER.AWS.AWS_DIM_PRODUCTS
TARGET_LAG = '10 minute'
WAREHOUSE = ELT_WAREHOUSE
AS
SELECT DISTINCT PRODUCT_ID AS AWS_PRODUCT_ID, PRODUCT_NAME AS AWS_PRODUCT_NAME, CATEGORY AS AWS_PRODUCT_CATEGORY, IMG_LINK AS AWS_IMG_LINK, PRODUCT_LINK AS AWS_PRODUCT_LINK FROM BRONZE.AWS.AWS_RAW_DATA;

-- Create a dynamic user dimension table
USE DATABASE SILVER;
CREATE OR REPLACE DYNAMIC TABLE SILVER.AWS.AWS_DIM_USER
TARGET_LAG = '10 minute'
WAREHOUSE = ELT_WAREHOUSE
AS
SELECT DISTINCT USER_ID AS AWS_USER_ID, USER_NAME AS AWS_USER_NAME FROM BRONZE.AWS.AWS_RAW_DATA;

-- Create a dynamic review dimension table
USE DATABASE SILVER;
CREATE OR REPLACE DYNAMIC TABLE SILVER.AWS.AWS_DIM_REVIEW
TARGET_LAG = '10 minute'
WAREHOUSE = ELT_WAREHOUSE
AS
SELECT DISTINCT REVIEW_ID AS AWS_REVIEW_ID, REVIEW_TITLE AS AWS_REVIEW_TITLE, REVIEW_CONTENT AS AWS_REVIEW_CONTENT FROM BRONZE.AWS.AWS_RAW_DATA;

-- Create a dynamic fact table
USE DATABASE SILVER;
CREATE OR REPLACE DYNAMIC TABLE SILVER.AWS.AWS_SALES_FACT_TABLE
TARGET_LAG = '10 minute'
WAREHOUSE = ELT_WAREHOUSE
AS
SELECT PRODUCT_ID AS AWS_PRODUCT_ID, ACTUAL_PRICE AS AWS_ACTUAL_PRICE, DISCOUNTED_PRICE AS AWS_DISCOUNTED_PRICE, DISCOUNT_PERCENTAGE AS AWS_DISCOUNT_PERCENTAGE, USER_ID AS AWS_USER_ID, REVIEW_ID AS AWS_REVIEW_ID FROM BRONZE.AWS.AWS_RAW_DATA;

-- Drop AWS_Raw_Data table
USE ROLE ORGADMIN;
USE DATABASE BRONZE
DROP TABLE AWS_RAW_DATA

-- Drop AWS_DIM_PRODUCTS Dynamic Table
USE ROLE ORGADMIN;
USE DATABASE SILVER
DROP DYNAMIC TABLE SILVER.AWS.AWS_RAW_DATA.AWS_DIM_PRODUCTS;

-- AWS_DIM_USER Dynamic Table
USE ROLE ORGADMIN;
USE DATABASE SILVER
DROP DYNAMIC TABLE SILVER.AWS.AWS_RAW_DATA.AWS_DIM_USER;

-- Drop AWS_DIM_REVIEW Dynamic Table
USE ROLE ORGADMIN;
USE DATABASE SILVER
DROP DYNAMIC TABLE SILVER.AWS.AWS_RAW_DATA.AWS_DIM_REVIEW;

-- Drop AWS_SALES_FACT_TABLE Dynamic Table
USE ROLE ORGADMIN;
USE DATABASE SILVER
DROP DYNAMIC TABLE SILVER.AWS.AWS_SALES_FACT_TABLE;

-- Drop Bronze AWS Schema
USE ROLE ORGADMIN;
USE DATABASE BRONZE
DROP SCHEMA AWS;

-- Drop Silver AWS Schema
USE ROLE ORGADMIN;
USE DATABASE SILVER
DROP SCHEMA BRONZE;

-- Drop Bronze Database
USE ROLE ORGADMIN;
DROP DATABASE BRONZE;

-- Drop Silver Database
USE ROLE ORGADMIN;
DROP DATABASE SILVER;